name: Destroy All Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm"
        required: true

jobs:
  destroy-resources:
    name: Destroy Application Resources
    runs-on: ubuntu-latest
    steps:
      #####################################################################
      # Step 1: Checkout, Setup Terraform, and Configure AWS Credentials
      #####################################################################
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: github-action

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      #####################################################################
      # Step 2: Initialize Terraform (Application Resources)
      #####################################################################
      - name: Initialize Terraform (Application Resources)
        run: terraform init
        working-directory: terraform/terraform_resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          # TF_LOG: DEBUG

      #####################################################################
      # Step 3: Destroy Application Resources (only if confirmed)
      #####################################################################
      - name: Destroy Application Resources
        if: ${{ github.event.inputs.confirm == 'destroy' }}
        run: terraform destroy --auto-approve
        working-directory: terraform/terraform_resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          # TF_LOG: DEBUG

      #####################################################################
      # (Optional) Post-Destruction Cleanup Step
      # Add any cleanup commands if needed here.
      #####################################################################
      - name: Cleanup Temporary Files (if any)
        if: ${{ github.event.inputs.confirm == 'destroy' }}
        run: echo "No temporary files to cleanup."

  destroy-backend:
    name: Destroy Backend Resources
    runs-on: ubuntu-latest
    needs: destroy-resources
    steps:
      #####################################################################
      # Step 1: Checkout, Setup Terraform, and Configure AWS Credentials
      #####################################################################
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: github-action

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      #####################################################################
      # Step 2: Initialize Terraform (Backend Resources) and Debug Connectivity
      #####################################################################
      - name: Initialize Terraform (Backend Resources)
        run: terraform init
        working-directory: terraform/terraform_backend
        env:
          TF_VAR_create_backend: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          # TF_LOG: DEBUG

      # Debug: List available S3 buckets to verify connectivity.
      - name: Debug - List S3 Buckets
        run: aws s3 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

      # Debug: List available DynamoDB tables to verify connectivity.
      - name: Debug - List DynamoDB Tables
        run: aws dynamodb list-tables
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

      #####################################################################
      # Step 3: Import, Empty, and Destroy Backend Resources (only if confirmed)
      #####################################################################
      - name: Import S3 Bucket (if exists)
        if: ${{ github.event.inputs.confirm == 'destroy' }}
        continue-on-error: true
        run: terraform import 'aws_s3_bucket.terraform_aws_s3_bucket[0]' ${{ secrets.AWS_S3_BUCKET }}
        working-directory: terraform/terraform_backend
        env:
          TF_VAR_create_backend: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          # TF_LOG: DEBUG

      - name: Import DynamoDB Table (if exists)
        if: ${{ github.event.inputs.confirm == 'destroy' }}
        continue-on-error: true
        run: terraform import 'aws_dynamodb_table.terraform_aws_db[0]' ${{ secrets.AWS_DYNAMODB_TABLE }}
        working-directory: terraform/terraform_backend
        env:
          TF_VAR_create_backend: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          # TF_LOG: DEBUG

      - name: Empty S3 Bucket
        if: ${{ github.event.inputs.confirm == 'destroy' }}
        run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }} --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

      - name: Destroy Backend Resources
        if: ${{ github.event.inputs.confirm == 'destroy' }}
        run: terraform destroy --auto-approve 
        working-directory: terraform/terraform_backend
        env:
          TF_VAR_create_backend: "true"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          # TF_LOG: DEBUG

  send-notification:
    name: Send Email Notification
    runs-on: ubuntu-latest
    needs: [destroy-resources, destroy-backend]
    if: always()  # Runs regardless of previous job outcomes
    steps:
      # 1) Determine overall pipeline status
      - name: Determine Pipeline Status
        id: pipeline-status
        run: |
          # We'll check the results of the two jobs we "need"
          # and create an output variable "result" accordingly.
          if [ "${{ needs.destroy-resources.result }}" = "success" ] && [ "${{ needs.destroy-backend.result }}" = "success" ]; then
            echo "result=Success ✅" >> $GITHUB_OUTPUT
          else
            echo "result=Failed ❌" >> $GITHUB_OUTPUT
          fi

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: ${{ secrets.MAIL_FROM }}
          to-email: <RECEIVER_EMAIL_ADDRESS>,<OHTER_RECEIVER_EMAIL_ADDRESS> # Add multiple email addresses separated by commas
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Destroy Workflow Notification: ${{ github.workflow }} - ${{ steps.pipeline-status.outputs.result }}"
          body: ""
          html: |
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; background-color: #ffffff;">
              <h2 style="color: #24292e; text-align: center;">🔥 Destroy Workflow Notification</h2>
              <div style="background-color: #f6f8fa; padding: 16px; border-radius: 6px;">
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Workflow</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">${{ github.workflow }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Triggered by</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">${{ github.actor }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Repository</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">${{ github.repository }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Run Details</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                      <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" style="color: #0366d6; text-decoration: none;">
                        View Run #${{ github.run_id }}
                      </a>
                    </td>
                  </tr>
                </table>
              </div>
              <h3 style="margin-top: 16px;">🛠 Job Statuses</h3>
              <table style="width: 100%; border-collapse: collapse; background-color: #fff;">
                <tr style="background-color: #f6f8fa;">
                  <th style="padding: 10px; text-align: left;">Job</th>
                  <th style="padding: 10px; text-align: center;">Status</th>
                </tr>
                <tr>
                  <td style="padding: 10px;">Destroy Application Resources</td>
                  <td style="padding: 10px; text-align: center; color: white; background-color: ${{ needs.destroy-resources.result == 'success' && '#28a745' || '#d73a49' }}; border-radius: 4px;">
                    ${{ needs.destroy-resources.result }}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 10px;">Destroy Backend Resources</td>
                  <td style="padding: 10px; text-align: center; color: white; background-color: ${{ needs.destroy-backend.result == 'success' && '#28a745' || '#d73a49' }}; border-radius: 4px;">
                    ${{ needs.destroy-backend.result }}
                  </td>
                </tr>
              </table>
              <p style="color: #6a737d; font-size: 0.9em; margin-top: 20px; text-align: center;">
                This email was sent automatically by <strong>GitHub Actions</strong>.
              </p>
            </div>